# -*- mode: ruby -*-
# vi: set ft=ruby :

# This Vagrantfile configures VMs globally. Settings can be overwritten with project specific settings. 
Vagrant.configure(2) do |config|
  config.vm.define :vm do | vm |
    # Add ~/.ssh/development/vagrantkey to ~/.ssh/authorized_keys at box creation time.
    # For public boxes vagrantkey is added at boot and always used since it appears first in private_key_path.
    vm.ssh.private_key_path = ["#{ENV['HOME']}/.ssh/development/vagrantkey",
                               "#{ENV['VAGRANT_HOME']}/insecure_private_key"]
    # Prevent vagrant generating new key when insecure key detected (custom provisioner does this!).
    vm.ssh.insert_key = false
  end

  config.vm.provider "virtualbox" do |vbox|
    vbox.customize ["modifyvm", :id, "--vram", "128"]
  end

  config.vm.provision "file", source: "#{ENV['HOME']}/.ssh/development/vagrantkey.pub", destination: "~/.ssh/authorized_keys"
end

