set nocompatible

source $DOTFILES_DIR/vim/keymappings.vim
set encoding=utf-8
syntax on

set term=screen-256color
colorscheme wombat256

" Show line numbers, relative to cursor.
" Cursor shows absolute line number.
set number
set relativenumber

" Expand tabs into spaces and use 2 spaces per tab.
set expandtab
set ts=2
set shiftwidth=2

" Show whitespace characters.
set list
set listchars=tab:▸\ ,eol:¬,trail:·

" Indent when moving to next line.
set autoindent

set clipboard=unnamedplus

set undofile
set nobackup

" Create missing directories.
silent execute '!mkdir -p $HOME/.vim/.{swaps,undo}'

" Trailing // creates matching absolute path in directory.
set undodir=~/.vim/.undo//
set directory=~/.vim/.swaps//