HERE=$HOME/.zshenv
SYSTEM_PATH="`dirname $(readlink -e -f $HERE)`/../system"

for DOTFILE in "$SYSTEM_PATH/"{function,env,path,alias}; do
	[ -f "$DOTFILE" ] && source "$DOTFILE"
done
unset DOTFILE

# Load non version controlled environment variables.
local EXTRA_ENV_PATH="$EXTRA_DIR/system/env"
[ -f "$EXTRA_ENV_PATH" ] && source "$EXTRA_ENV_PATH"
