ZSH=$HOME/.oh-my-zsh
ZSH_CUSTOM=$DOTFILES_DIR/base/zsh/customization/
ZSH_THEME="custom"

if [[ -n $SSH_CONNECTION ]]; then
  ZSH_THEME="custom_ssh"
else
  ZSH_THEME="custom"
fi

# Prevent weekly auto updates.
DISABLE_AUTO_UPDATE=true

plugins=(zsh-syntax-highlighting history-substring-search web-search)

source $ZSH/oh-my-zsh.sh

export TERM="xterm-256color"
export EDITOR="vim"
export USE_EDITOR=$EDITOR
export VISUAL=$EDITOR

# Sanity check for "rm *".
setopt RM_STAR_WAIT

# Use spelling correction.
setopt CORRECT	

# Disable less history.
LESSHISTFILE=/dev/null

GPG_TTY=$(tty)
export GPG_TTY

umask 007
