# Parameter 1 should be a directory possibly containing files where filename is included in variable FILES below.
function source_system_config_files
{
  PARENT_DIRECTORY="$1"
  FILES=("function" "env" "path" "alias")
  for CFG_FILE in "$FILES[@]"; do
    FILE_PATH="$PARENT_DIRECTORY/$CFG_FILE"
    [ -f "$FILE_PATH" ] && source "$FILE_PATH"
  done
  unset FILE_PATH
  unset CFG_FILE
}

# Since $DOTFILES_DIR is set after sourcing, path needs to be calculated.
HERE=$HOME/.zshenv
SYSTEM_PATH="`dirname $(readlink -e -f $HERE)`/../system"
source_system_config_files "$SYSTEM_PATH"

# Load privately version controlled config files.
source_system_config_files "$EXTRA_DIR/system"
