ZSH=$HOME/.oh-my-zsh
ZSH_THEME="agnoster"

# Prevent weekly auto updates.
DISABLE_AUTO_UPDATE=false

plugins=(zsh-autosuggestions zsh-syntax-highlighting history-substring-search web-search colored-man-pages docker-compose docker)
autoload -Uz compinit && compinit

source $ZSH/oh-my-zsh.sh

export EDITOR="vim"
export USE_EDITOR=$EDITOR
export VISUAL=$EDITOR

# Sanity check for "rm *".
setopt RM_STAR_WAIT

# Use spelling correction.
setopt CORRECT

# Set history timestamp format
HIST_STAMPS="%d/%m/%y %T"

# Prevent duplicates in history
setopt hist_ignore_all_dups hist_save_nodups
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY


# Disable less history.
LESSHISTFILE=/dev/null

GPG_TTY=$(tty)
export GPG_TTY

umask 007

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# zsh parameter completion for the dotnet CLI
_dotnet_zsh_complete()
{
  local completions=("$(dotnet complete "$words")")
  reply=( "${(ps:\n:)completions}" )
}
compctl -K _dotnet_zsh_complete dotnet

# Only show cwd in terminal
prompt_context() {}

# Initialize only and only one ssh-agent
if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent -t 1h > "$XDG_RUNTIME_DIR/ssh-agent.env"
fi
if [[ ! "$SSH_AUTH_SOCK" ]]; then
    source "$XDG_RUNTIME_DIR/ssh-agent.env" >/dev/null
fi

PROMPT='%{$fg[yellow]%}[%D{%Y-%m-%d} %D{%H:%M:%S}] '$PROMPT

compinit
