ZSH=$HOME/.oh-my-zsh
ZSH_THEME="agnoster"

# Prevent weekly auto updates.
DISABLE_AUTO_UPDATE=true

plugins=(history-substring-search web-search colored-man-pages docker-compose docker-machine docker)

source $ZSH/oh-my-zsh.sh

export EDITOR="vim"
export USE_EDITOR=$EDITOR
export VISUAL=$EDITOR

# Sanity check for "rm *".
setopt RM_STAR_WAIT

# Use spelling correction.
setopt CORRECT

# Prevent duplicates in history
setopt hist_ignore_all_dups hist_save_nodups

# Disable less history.
LESSHISTFILE=/dev/null

GPG_TTY=$(tty)
export GPG_TTY

umask 007

eval `dircolors ~/.dir_colors/dircolors`
# Only show cwd in terminal
prompt_context() {}

source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
